### ISSUE TITLE
Boostraped migrations

### ISSUE THREAD

**Issue by ThibaudDauce** [TeamHG-Memex/agnostic#6]
Hi,

When I bootstrap agnostic, it fills the `agnostic_migrations` table with my migrations with a "boostrapped" status. And then, when I try to run the `migrate` command, it tells me "There are no pending migrations." but my migrations were never run.

**Comment by mehaase** [comment]
This is intentional. You probably want to run `agnostic bootstrap --no-bootstrap-existing`. The details about why you would do that are here: http://agnostic.readthedocs.io/en/latest/design.html#build-vs-migrate

**Comment by ThibaudDauce** [comment]
Thanks for the option! (it's `no-load-existing` instead of `no-bootstrap-existing` but it did what I wanted ^^)
